name: Build Test
on: push
#   push:
#     branches:
#     - 'ros2'
#   pull_request:
#     branches:
#     - '*'

jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        config:
          - {rosdistro: 'humble', container: 'osrf/ros:humble-desktop'}
    container: ${{ matrix.config.container }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path: src/ethz-asl/terrain-navigation
    - name: Check out source dependencies with vcs
      run: |
        cd src
        vcs import --recursive --debug --shallow --skip-existing < src/ethz-asl/terrain-navigation/terrain-navigation.repos
      shell: bash
    - name: Install binary dependencies with rosdep
      run: |
        apt update
        rosdep update
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths src --ignore-src -y --rosdistro ${{matrix.config.rosdistro}}
      shell: bash
    - name: Build with colcon
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to terrain_navigation_ros
      shell: bash
    - name: Run tests
      working-directory:
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --paths src/ethz-asl/terrain-navigation --event-handlers=console_cohesion+
        colcon test-result --all --verbose
      shell: bash
